## Basic Configuration
baseurl = "https://amk.netlify.com/"
languageCode = "en"

title = ""
theme = "hyde-hyde"
    
## Hugo Built-in Features
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
# disqusShortname = "amkblog"
relativeURLs = true
googleAnalytics = "UA-148162328-1"
# enableRobotsTXT = true

## Site Settings
[params]
    author = "Alayna, Mary, Kim"
    themeColor = "theme-base-0d"
    # title = "Title"
    description = "We seek inspirational stories from all walks of life to share in order to spark personal and professional growth."
    authorimage = "/img/amk-logo.png"
    dateformat = "Jan 2, 2006"
    highlightjs = true
    highlightjsstyle = "github"
    math = true
    copyright = "&copy; 2019. All rights reserved."


## Social Accounts
[params.social]
    # github = "kykimeng"
    instagram = "amk.platform"
    #xing = "<username>"
    #linkedin = "kykimeng"
    #twitter = "kimmyky2"
    facebook = "amkplatform"
    #stackoverflow = "<username>"
    #telegram = "<username>"
    email = "amkplatform@gmail.com"

## Main Menu
[[menu.main]]
    name = "Home"
    weight = 5
    identifier = ""
    url = "/"
[[menu.main]]
    name = "About Us"
    weight = 10
    identifier = "about"
    url = "/about/"
[[menu.main]]
    name = "Blog Posts"
    weight = 20
    identifier = "posts"
    url = "/posts/"
