theme = "hyde"
baseURL = "https://amk.netlify.com/"
languageCode = "en-us"
title = "A.M.K"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
relativeURLs = true

## Site Settings
[params]
    author = "A.M.K"
    themeColor = "theme-base-0d"
    # title = "Title"
    description = "We seek inspirational stories from all walks of life to share in order to spark personal and professional growth."
    authorimage = "/img/amk-logo.png"
    dateformat = "Jan 2, 2006"
    highlightjs = true
    highlightjsstyle = "github"
    math = true
    copyright = "&copy; 2018. All rights reserved."
    
[[menu.main]]
    name = "About Us"
    identifier = "about"
    weight = 10
    url = "/about/"
    
[[menu.main]]
    name = "Blog Posts"
    weight = 20
    identifier = "post"
    url = "/post/"